### PR TITLE
Build with bundled jsonparser

### PR DESCRIPTION
**Pull request by jelmer**

### CODE REVIEW

**Comment by robert-scheck** [comment]
I would like to support this if you let me know which way is preferred: With bundled jsonparser…or with system one?

**Comment by jelmer** [comment]
> I would like to support this if you let me know which way is preferred: With bundled jsonparser…or with system one?

This PR was meant to fix the build on GH actions, which currently fails. Unfortunately we can't just disable the build with system jsonparser as that breaks the Debian package.

**Comment by robert-scheck** [comment]
Well, what is the desired outcome for the Debian package? Bundled or system jsonparser?

**Comment by jelmer** [comment]
it should use the system jsonparser

**Pull request closed without merging**
