### PR TITLE
Add Mastodon support

### PR DESCRIPTION
**Pull request by kensanata**
I think this is ready for code review. Sadly, I wasn't able to run this under valgrind using macOS Sierra, so I'm suspecting leaks. :(

### CODE REVIEW

**Comment by kensanata** [comment]
I have a bunch of commits in a [new branch](https://github.com/kensanata/bitlbee/commits/features/kensanata/mastodon-extra-features) which I'm holding back for the moment. On the other hand, if you haven't started reviewing this Pull Request, maybe I could just add them to it? Better to look at it just once?

**Comment by kensanata** [comment]
Rebased on `upstream/develop` branch after the two Twitter patches got merged.

**Comment by kensanata** [comment]
Rebased on `upstream/develop` branch. I will also be mostly offline for some weeks, soon.

**Comment by dequis** [comment]
The mastodon_http.c changes relative to twitter's version make me sad :(

Mostly the refactoring in 3092ee6505b5262877d0569b6e996a1d476a0752, nothing wrong with the final version but those changes "just because" make it harder to review.

**Comment by kensanata** [comment]
I'm back from my trip! Is there anything I can do? I guess the alternative would be to have `mastodon_http` take an `is_post` parameter that can 0, 1 or 2 and just add the functionality for DELETE requests?

**Comment by kensanata** [comment]
Ugh. I just found that for Mastodon 2.0 they changed all the ids from integer to strings… 💩 
Marking this as "WIP".

**Comment by dequis** [comment]
I don't know, this is massive and I have no time nor energy to review all of it. These last few weeks have been real busy for me (haven't even had time to fix security issues in [REDACTED]) aaaand i'm leaving for a 3-week trip in 4 days.

Consider packaging it as a standalone plugin, at least for now.

Otherwise, if you really want it to be built-in, I really would prefer integrating as much code as possible with the existing twitter plugin - that one already exposes two protocols (twitter and identica), admittedly almost identical ones. I don't know if that is a reasonable request. You could also consider adding more things to lib/ - twitter's http thing really could use moving there, if it's generic enough. (Or the bitlbee-steam one, or the bitlbee-facebook one). The http stuff is just an example though, the easiest thing to pick apart from this.

BTW, one of my plans for bitlbee is to eventually migrate to json-glib and make that a dependency for bitlbee, since it's in all major distros by now. Haven't had the time to do so, but keep it in mind. On that topic I also would like to depend on a saner third-party http library, but that's trickier and not decided yet

**Comment by kensanata** [comment]
I understand lack of energy but I'm still sad. :(
I'll take a look at rewriting it as a plugin. I've seen the Facebook and Discord plugins so I a template, at least.

**Comment by kensanata** [comment]
Anybody coming here looking for Mastodon support, checkout the [Mastodon plugin](https://github.com/kensanata/bitlbee-mastodon).

**Pull request closed without merging**
