### PR TITLE
Add --verbose configure option to control verbose build output

### PR DESCRIPTION
**Pull request by radhermit**
Defaults to disabled to maintain the status quo.

### CODE REVIEW

**Comment by dequis** [comment]
Yeah we needed something like this. I think it would be nicer to make it more like autotools:

```
  --enable-silent-rules   less verbose build output (undo: "make V=1")
  --disable-silent-rules  verbose build output (undo: "make V=0")
```

And set the real value of verbose (`@` or nothing) with an ifeq block based on `V`.

**Comment by dequis** [comment]
Ooooon the other hand `--verbose=1` is more consistent with the rest of bitlbee's configure so uh maybe just do the `make V=1` thing? I like `make V=1`

**Comment by radhermit** [comment]
How about something like that?

**Comment by dequis** [comment]
Seems that I forgot to post my comment. Not a huge fan of having logic in Makefile.settings but I can't come up with anything better so it's fine. I'll merge this later.

**Comment by jgeboski** [comment]
It's really not that much logic. This seems quite sane to me.

**Comment by dequis** [comment]
Thanks! Sorry for the delay.

**Pull request merged**
