### PR TITLE
Fix some issues reported by lintian

### PR DESCRIPTION
**Pull request by debian-janitor**
Fix some issues reported by lintian
* Use secure URI in debian/watch.
* Use secure URI in Homepage field.
* Add missing colon in closes line.
* Bump debhelper from old 10 to 12.
* Upgrade to newer source format.

This merge proposal was created automatically by the Janitor bot
(https://janitor.debian.net/lintian-fixes).

You can follow up to this merge proposal as you normally would.

Build and test logs for this branch can be found at
https://janitor.debian.net/lintian-fixes/pkg/bitlbee/90e47edd-521e-476a-80a2-92f93d5b5553/.

### CODE REVIEW

**Comment by dequis** [comment]
"Bump debhelper from old 10 to 12." lol

**Comment by jelmer** [comment]
That's just the pull request description though :)

**Comment by dequis** [comment]
Yeah I just find it funny how it keeps appearing

**Comment by dequis** [comment]
"dpkg-source: error: can't build with source format '3.0 (quilt)': no upstream tarball found at ../bitlbee_3.6.orig.tar.{bz2,gz,lzma,xz}"

This broke travis

**Comment by dequis** [comment]
Ignore the commit reference above, i found a proper fix in the second commit of https://github.com/bitlbee/bitlbee/pull/139

**Pull request merged**
