### PR TITLE
twitter: switch to an app that didn't get murdered yet

### PR DESCRIPTION
**Pull request by dequis**
Wonder how long this will last, probably not very.

### CODE REVIEW

**Comment by dequis** [comment]
image

very legit

**Review by jelmer — APPROVED** [review]

**Comment by ilf** [comment]
Thanks for this!

Is this adjustable without changing it in the source and recompiling?

Would this warrant a release, like 3.6.1 or 3.7?

Thanks!

**Comment by jelmer** [comment]
> Thanks for this!
> 
> Is this adjustable without changing it in the source and recompiling?

It's not currently adjustable, but I suppose we could add a separate setting for it? Having to create your own app isn't a great experience, though.

**Comment by ilf** [comment]
Looking at other Apps and Twitters erratic behavior, it looks like users might have to change App keys more frequently in the near future and maybe use keys that are not shared widely. So an option to change this without editing the source and recompiling sure would be useful.

In the medium future, Twitter will probably just kill all third party apps and keys, though.

**Comment by Wilm0r** [comment]
Yeah, I guess this will need to be a setting from now on (and leave it up to the user whether to request a key or try out one of the official-app ones, if that's still possible?), and we'll see how many weeks/months before we can just delete the module altogether.

It's nice that at least Twitter became mostly irrelevant already *before* locking all the doors now.

**Comment by dequis** [comment]
>try out one of the official-app ones, if that's still possible?

It's not, otherwise i would have used one of those in this commit.

**Pull request merged**
