### PR TITLE
Properly terminate bitlbee with systemctl

### PR DESCRIPTION
**Pull request by Perdu**
Fixes the bug I posted here: https://bugs.bitlbee.org/ticket/1323

Environment : archlinux

Additional plugin: bitlbee-facebook

Steps to reproduce:
- verify that 0 bitlbee processes are running
- `$ sudo systemctl start bitlbee`
- connect to bitlbee server
- observe that 3 bitlbee processes are running
- `$ sudo systemctl stop bitlbee`
- 2 bitlbee processes remain

### CODE REVIEW

**Comment by dequis** [comment]
Yeah, uh, sorry, that's not a bug, that's a feature.

`control-group` is the default value for KillMode if that line is missing, and I added that line to introduce this behavior [in this commit](https://github.com/bitlbee/bitlbee/commit/ad5a9078ff68c2556a2b692855f04938efc06e3d).

The idea is to allow restarting the daemon during package updates etc and not kill existing sessions. `sshd` works the same way.

**Comment by Perdu** [comment]
I see, but it does have the side-effect of breaking `systemctl stop` normal functioning. Could other options such as `Restart=` or `ExecReload=` achieve the same purpose without side-effect?

**Comment by dequis** [comment]
No idea! It's complicated. Closing this since it's going nowhere. Sorry for that.

**Comment by Thaodan** [comment]
is this a workaround for some debian thing? Systemd doesn't restart deamons on upgrading them with the package manager. Restarting bitlbee should restart the whole daemon.

**Comment by Perdu** [comment]
"Environment : archlinux"

**Comment by Thaodan** [comment]
> "Environment : archlinux"

The comment referred too the comment below sorry for the noise.
The point this workaround breaks restarting bitlbee using systemd, your changes fixes that.


> Yeah, uh, sorry, that's not a bug, that's a feature.
> 
> `control-group` is the default value for KillMode if that line is missing, and I added that line to introduce this behavior [in this commit](https://github.com/bitlbee/bitlbee/commit/ad5a9078ff68c2556a2b692855f04938efc06e3d).
> 
> The idea is to allow restarting the daemon during package updates etc and not kill existing sessions. `sshd` works the same way.

**Pull request closed without merging**
