### PR TITLE
purple: add topic and name_hint to groupchats

### PR DESCRIPTION
**Pull request by seirl**
Use imcb_chat_name_hint and imcb_chat_topic for the purple groupchats by using the PurpleConversation 'title' attribute.

### CODE REVIEW

**Comment by dequis** [comment]
:+1:

**Comment by jgeboski** [comment]
Is it ever possible that `conv->title` is going to be `NULL`?  If so, wrap `imcb_chat_name_hint()` and `imcb_chat_topic()` in a conditional block.  Those functions do not gracefully handle `NULL` strings.

**Comment by dequis** [comment]
Okay the patch is at +6 lines now, this means our possibilities to nitpick are duplicated. This is a bit hard though, all I can think is that the `!= NULL` is a bit redundant but I don't want to use that card yet and run out of nitpicks. @jgeboski any ideas?

**Comment by jgeboski** [comment]
I completely agree with comparing to `NULL`.  That said, I don't think most of bitlbee compares against `NULL`, so it should probably be kept consistent.

**Comment by dequis** [comment]
Are you saying we're out of nitpicks? :(

**Comment by Wilm0r** [comment]
YES WE ARE!

**Comment by Wilm0r** [comment]
(Though topics can be long so the long yet truncated life stories as channel names are going to be hilarious. But it beats #chat_000.

**Comment by dequis** [comment]
Nitpick: missing a `)`

**Pull request merged**
