### PR TITLE
purple: allow libpurple message processing before passing to bitlbee.

### PR DESCRIPTION
**Pull request by event**
Remove write_im and write_chat callbacks. Do all handling in write_conv.
This way message is passed through standard libpurple processing (incl. logging) prior to bitlbee handling

### CODE REVIEW

**Comment by dequis** [comment]
>standard libpurple processing (incl. logging)

Is the purpose of this change to enable logging, or what?

Seems odd that implementing uiops would have that effect, i'll have a deeper look at this later.

**Comment by dequis** [comment]
Did you test this? Every message i send in both private and groupchats gets me the same message echoed back

**Comment by event** [comment]
I did, but apparently not good enough. I'll have this fixed and place another request.

**Comment by dequis** [comment]
You can update pull requests by pushing to the same branch, no need to open a new one

I still would like to know why you're doing this.

**Pull request closed without merging**
