### PR TITLE
[debian] Replace netstat by ss

### PR DESCRIPTION
**Pull request by jspricke**
Also replace the dependency on net-tools by iproute2.
See: https://lists.debian.org/debian-devel/2016/12/msg00604.html

### CODE REVIEW

**Comment by jelmer** [comment]
Is there something we could use that would also work on e.g. kfreebsd-{amd64,i386}? netstat is at least provided by both net-tools and freebsd-net-tools.

**Comment by jspricke** [comment]
Good point, `sockstat -l` should work for both systems, but does not list IPv6 on Linux in the current version. The other option would be to test for the available tool first. What would you prefer?

**Comment by dequis** [comment]
Isn't /etc/default/ stuff ignored with systemd? Dropping the whole thing might be an option too. Or set it to 6667 and don't try to be clever about it.

**Comment by jspricke** [comment]
Seems like, should I simply remove it?

**Comment by jelmer** [comment]
Not trying to be clever about it seems reasonable to me too. It's nice to be consistent across init systems too.

**Comment by jspricke** [comment]
I've updated the pull request accordingly.

**Comment by jelmer** [comment]
You probably also want to update README.Debian to mention the new rather than the old behaviour.

**Pull request merged**
